((docgrep-in-doc (("0" . "greek")))
 (recent-buffer
   (("0"
     .
     "tmfs://help/book/tm/doc/main/man-user-manual.en.tm"))
   (("0"
     .
     "tmfs://help/article/tm/doc/main/start/man-getting-started.en.tm"))
   (("0"
     .
     "tmfs://help/article/tm/doc/main/config/man-preferences.en.tm"))
   (("0"
     .
     "tmfs://help/article/tm/doc/main/config/man-config-keyboard.en.tm"))
   (("0"
     .
     "/Applications/TeXmacs-1.99.4.app/Contents/Resources/share/TeXmacs/doc/main/math/keyboard/man-symbols.en.tm"))
   (("0" . "tmfs://grep/type=doc&what=greek"))
   (("0"
     .
     "tmfs://help/normal/tm/doc/devel/format/regular/prim-math.en.tm"))
   (("0"
     .
     "tmfs://help/normal/tm/doc/devel/format/regular/regular.en.tm"))
   (("0"
     .
     "tmfs://help/normal/tm/doc/devel/format/environment/env-general.en.tm"))
   (("0"
     .
     "tmfs://help/normal/tm/doc/devel/format/environment/environment.en.tm"))
   (("0"
     .
     "tmfs://help/normal/tm/doc/main/man-reference.en.tm"))
   (("0"
     .
     "tmfs://help/normal/tm/doc/about/welcome/welcome.en.tm"))
   (("0"
     .
     "tmfs://help/article/tm/doc/main/math/man-math.en.tm"))
   (("0"
     .
     "tmfs://help/article/tm/doc/main/text/man-text.en.tm"))
   (("0"
     .
     "tmfs://help/article/tm/doc/devel/style/style.en.tm"))
   (("0" . "/Applications/TeX/texmacs/proof.tm")))
 (wrapped-print-to-file
   (("0"
     system->url
     "/Applications/TeX/texmacs/manual.pdf"))
   (("0"
     system->url
     "/Applications/TeX/texmacs/Untitled.pdf"))))
