("abscissa Document page format" "341")
("abscissa Font selector" "239")
("abscissa Macro editor" "341")
("abscissa Paragraph format" "341")
("abscissa TeXmacs" "112")
("abscissa User preferences" "51")
("height Document page format" "505")
("height Font selector" "697")
("height Macro editor" "385")
("height Paragraph format" "417")
("height TeXmacs" "584")
("height User preferences" "221")
("look and feel" "macos")
("ordinate Document page format" "208")
("ordinate Font selector" "22")
("ordinate Macro editor" "208")
("ordinate Paragraph format" "208")
("ordinate TeXmacs" "90")
("ordinate User preferences" "156")
("width Document page format" "762")
("width Font selector" "886")
("width Macro editor" "656")
("width Paragraph format" "395")
("width TeXmacs" "800")
("width User preferences" "443")
