((Al\ Bayan Bold) ((AlBayanBold.ttf 0)))
((Al\ Bayan Plain) ((AlBayan.ttf 0)))
((American\ Typewriter Bold) ((AmericanTypewriter.ttc 1)))
((American\ Typewriter Condensed) ((AmericanTypewriter.ttc 4)))
((American\ Typewriter Condensed\ Bold) ((AmericanTypewriter.ttc 2)))
((American\ Typewriter Condensed\ Light) ((AmericanTypewriter.ttc 5)))
((American\ Typewriter Light) ((AmericanTypewriter.ttc 3)))
((American\ Typewriter Regular) ((AmericanTypewriter.ttc 0)))
((Andale\ Mono Regular) ((Andale\ Mono.ttf 0)))
((Apple\ Braille Outline\ 6\ Dot) ((Apple\ Braille\ Outline\ 6\ Dot.ttf 0)))
((Apple\ Braille Outline\ 8\ Dot) ((Apple\ Braille\ Outline\ 8\ Dot.ttf 0)))
((Apple\ Braille Pinpoint\ 6\ Dot) ((Apple\ Braille\ Pinpoint\ 6\ Dot.ttf 0)))
((Apple\ Braille Pinpoint\ 8\ Dot) ((Apple\ Braille\ Pinpoint\ 8\ Dot.ttf 0)))
((Apple\ Braille Regular) ((Apple\ Braille.ttf 0)))
((Apple\ Chancery Chancery) ((Apple\ Chancery.ttf 0)))
((Apple\ LiGothic Medium) ((Apple\ LiGothic\ Medium.ttf 0)))
((Apple\ LiSung Light) ((Apple\ LiSung\ Light.ttf 0)))
((Apple\ Symbols Regular) ((Apple\ Symbols.ttf 0)))
((AppleGothic Regular) ((AppleGothic.ttf 0)))
((Aqua\ Kana Bold) ((AquaKana.ttc 1)))
((Aqua\ Kana Regular) ((AquaKana.ttc 0)))
((Arial Bold) ((Arial\ Bold.ttf 0)))
((Arial Bold\ Italic) ((Arial\ Bold\ Italic.ttf 0)))
((Arial Italic) ((Arial\ Italic.ttf 0)))
((Arial\ Black Regular) ((Arial\ Black.ttf 0)))
((Arial\ Narrow Bold) ((Arial\ Narrow\ Bold.ttf 0)))
((Arial\ Narrow Bold\ Italic) ((Arial\ Narrow\ Bold\ Italic.ttf 0)))
((Arial\ Narrow Italic) ((Arial\ Narrow\ Italic.ttf 0)))
((Arial\ Narrow Regular) ((Arial\ Narrow.ttf 0)))
((Arial\ Rounded\ MT\ Bold Regular) ((Arial\ Rounded\ Bold.ttf 0)))
((Arial\ Unicode\ MS Regular) ((Arial\ Unicode.ttf 0)))
((Ayuthaya Regular) ((Ayuthaya.ttf 0)))
((Baghdad Regular) ((Baghdad.ttf 0)))
((Baskerville Bold) ((Baskerville.ttc 1)))
((Baskerville Bold\ Italic) ((Baskerville.ttc 4)))
((Baskerville Italic) ((Baskerville.ttc 2)))
((Baskerville Regular) ((Baskerville.ttc 0)))
((Baskerville SemiBold) ((Baskerville.ttc 5)))
((Baskerville SemiBold\ Italic) ((Baskerville.ttc 3)))
((BiauKai Regular) ((BiauKai.ttf 0)))
((Big\ Caslon Medium) ((BigCaslon.ttf 0)))
((Brush\ Script\ MT Italic) ((Brush\ Script.ttf 0)))
((Chalkboard Bold) ((Chalkboard.ttc 1)))
((Chalkboard Regular) ((Chalkboard.ttc 0)))
((Chalkduster Regular) ((Chalkduster.ttf 0)))
((Cochin Bold) ((Cochin.ttc 1)))
((Cochin Bold\ Italic) ((Cochin.ttc 3)))
((Cochin Italic) ((Cochin.ttc 2)))
((Cochin Regular) ((Cochin.ttc 0)))
((Comic\ Sans\ MS Bold) ((Comic\ Sans\ MS\ Bold.ttf 0)))
((Comic\ Sans\ MS Regular) ((Comic\ Sans\ MS.ttf 0)))
((Copperplate Bold) ((Copperplate.ttc 2)))
((Copperplate Light) ((Copperplate.ttc 1)))
((Copperplate Regular) ((Copperplate.ttc 0)))
((Courier\ New Bold) ((Courier\ New\ Bold.ttf 0)))
((Courier\ New Bold\ Italic) ((Courier\ New\ Bold\ Italic.ttf 0)))
((Courier\ New Italic) ((Courier\ New\ Italic.ttf 0)))
((Courier\ New Regular) ((Courier\ New.ttf 0)))
((DecoType\ Naskh Regular) ((DecoTypeNaskh.ttf 0)))
((Devanagari\ MT Bold) ((DevanagariMTBold.ttf 0)))
((Devanagari\ MT Regular) ((DevanagariMT.ttf 0)))
((Didot Bold) ((Didot.ttc 2)))
((Didot Italic) ((Didot.ttc 1)))
((Didot Regular) ((Didot.ttc 0)))
((Futura Condensed\ ExtraBold) ((Futura.ttc 3)))
((Futura Condensed\ Medium) ((Futura.ttc 2)))
((Futura Medium) ((Futura.ttc 0)))
((Futura Medium\ Italic) ((Futura.ttc 1)))
((Geeza\ Pro Bold) ((Geeza\ Pro\ Bold.ttf 0)))
((Geeza\ Pro Regular) ((Geeza\ Pro.ttf 0)))
((Georgia Bold) ((Georgia\ Bold.ttf 0)))
((Georgia Bold\ Italic) ((Georgia\ Bold\ Italic.ttf 0)))
((Georgia Italic) ((Georgia\ Italic.ttf 0)))
((Georgia Regular) ((Georgia.ttf 0)))
((Gill\ Sans Bold) ((GillSans.ttc 1)))
((Gill\ Sans Bold\ Italic) ((GillSans.ttc 2)))
((Gill\ Sans Italic) ((GillSans.ttc 3)))
((Gill\ Sans Light) ((GillSans.ttc 4)))
((Gill\ Sans Light\ Italic) ((GillSans.ttc 5)))
((Gill\ Sans Regular) ((GillSans.ttc 0)))
((Gujarati\ MT Bold) ((GujaratiMTBold.ttf 0)))
((Gujarati\ MT Regular) ((GujaratiMT.ttf 0)))
((Gurmukhi\ MT Regular) ((Gurmukhi.ttf 0)))
((HeadLineA Regular) ((HeadlineA.ttf 0)))
((Hei Regular) ((Hei.ttf 0)))
((Heiti\ SC Light) ((STHeiti\ Light.ttc 1)))
((Heiti\ SC Medium) ((STHeiti\ Medium.ttc 1)))
((Heiti\ TC Light) ((STHeiti\ Light.ttc 0)))
((Heiti\ TC Medium) ((STHeiti\ Medium.ttc 0)))
((Herculanum Regular) ((Herculanum.ttf 0)))
((Hiragino\ Kaku\ Gothic\ Pro W3) ((ヒラギノ角ゴ\ Pro\ W3.otf 0)))
((Hiragino\ Kaku\ Gothic\ Pro W6) ((ヒラギノ角ゴ\ Pro\ W6.otf 0)))
((Hiragino\ Kaku\ Gothic\ ProN W3) ((ヒラギノ角ゴ\ ProN\ W3.otf 0)))
((Hiragino\ Kaku\ Gothic\ ProN W6) ((ヒラギノ角ゴ\ ProN\ W6.otf 0)))
((Hiragino\ Kaku\ Gothic\ Std W8) ((ヒラギノ角ゴ\ Std\ W8.otf 0)))
((Hiragino\ Kaku\ Gothic\ StdN W8) ((ヒラギノ角ゴ\ StdN\ W8.otf 0)))
((Hiragino\ Maru\ Gothic\ Pro W4) ((ヒラギノ丸ゴ\ Pro\ W4.otf 0)))
((Hiragino\ Maru\ Gothic\ ProN W4) ((ヒラギノ丸ゴ\ ProN\ W4.otf 0)))
((Hiragino\ Mincho\ Pro W3) ((ヒラギノ明朝\ Pro\ W3.otf 0)))
((Hiragino\ Mincho\ Pro W6) ((ヒラギノ明朝\ Pro\ W6.otf 0)))
((Hiragino\ Mincho\ ProN W3) ((ヒラギノ明朝\ ProN\ W3.otf 0)))
((Hiragino\ Mincho\ ProN W6) ((ヒラギノ明朝\ ProN\ W6.otf 0)))
((Hiragino\ Sans\ GB W3) ((Hiragino\ Sans\ GB\ W3.otf 0)))
((Hiragino\ Sans\ GB W6) ((Hiragino\ Sans\ GB\ W6.otf 0)))
((Hoefler\ Text Black) ((Hoefler\ Text.ttc 1)))
((Hoefler\ Text Black\ Italic) ((Hoefler\ Text.ttc 3)))
((Hoefler\ Text Italic) ((Hoefler\ Text.ttc 2)))
((Hoefler\ Text Ornaments) ((Hoefler\ Text\ Ornaments.ttf 0)))
((Hoefler\ Text Regular) ((Hoefler\ Text.ttc 0)))
((Impact Regular) ((Impact.ttf 0)))
((InaiMathi Regular) ((InaiMathi.ttf 0)))
((Kai Regular) ((Kai.ttf 0)))
((Kailasa Regular) ((Kailasa.ttf 0)))
((Keyboard Regular) ((Keyboard.ttf 0)))
((Kokonor Regular) ((Kokonor.ttf 0)))
((Krungthep Regular) ((Krungthep.ttf 0)))
((KufiStandardGK Regular) ((KufiStandardGK.ttf 0)))
((LastResort Regular) ((LastResort.ttf 0)))
((LiHei\ Pro Medium) ((儷黑\ Pro.ttf 0)))
((LiSong\ Pro Light) ((儷宋\ Pro.ttf 0)))
((Lucida\ Grande Bold) ((LucidaGrande.ttc 1)))
((Lucida\ Grande Regular) ((LucidaGrande.ttc 0)))
((Marker\ Felt Thin) ((MarkerFelt.ttc 0)))
((Marker\ Felt Wide) ((MarkerFelt.ttc 1)))
((Menlo Bold) ((Menlo.ttc 1)))
((Menlo Bold\ Italic) ((Menlo.ttc 3)))
((Menlo Italic) ((Menlo.ttc 2)))
((Menlo Regular) ((Menlo.ttc 0)))
((Microsoft\ Sans\ Serif Regular) ((Microsoft\ Sans\ Serif.ttf 0)))
((Mshtakan Bold) ((MshtakanBold.ttf 0)))
((Mshtakan BoldOblique) ((MshtakanBoldOblique.ttf 0)))
((Mshtakan Oblique) ((MshtakanOblique.ttf 0)))
((Mshtakan Regular) ((MshtakanRegular.ttf 0)))
((Nadeem Regular) ((Nadeem.ttf 0)))
((Optima Bold) ((Optima.ttc 1)))
((Optima Bold\ Italic) ((Optima.ttc 3)))
((Optima ExtraBlack) ((Optima.ttc 4)))
((Optima Italic) ((Optima.ttc 2)))
((Optima Regular) ((Optima.ttc 0)))
((Osaka Regular) ((Osaka.ttf 0)))
((Osaka Regular-Mono) ((OsakaMono.ttf 0)))
((Papyrus Condensed) ((Papyrus.ttc 1)))
((Papyrus Regular) ((Papyrus.ttc 0)))
((PCMyungjo Regular) ((PCmyoungjo.ttf 0)))
((PilGi Regular) ((Pilgiche.ttf 0)))
((Plantagenet\ Cherokee Regular) ((PlantagenetCherokee.ttf 0)))
((Sathu Regular) ((Sathu.ttf 0)))
((Silom Regular) ((Silom.ttf 0)))
((Skia Regular) ((Skia.ttf 0)))
((STFangsong Regular) ((华文仿宋.ttf 0)))
((STHeiti Light) ((华文细黑.ttf 0)))
((STHeiti Regular) ((华文黑体.ttf 0)))
((Stix Bold) ((STIX-Bold.otf 0)))
((Stix Bold\ Italic) ((STIX-BoldItalic.otf 0)))
((Stix Italic) ((STIX-Italic.otf 0)))
((Stix Regular) ((STIX-Regular.otf 0)))
((Stix\ Math Regular) ((STIXMath-Regular.otf 0)))
((Symbol Regular) ((Symbol.ttf 0)))
((Tahoma Bold) ((Tahoma\ Bold.ttf 0)))
((Tahoma Regular) ((Tahoma.ttf 0)))
((TeX\ AMS\ Blackboard\ Bold Regular) ((msbm10.tfm 0)))
((TeX\ Blackboard\ Bold Bold) ((bbmbx10.tfm 0)))
((TeX\ Blackboard\ Bold Oblique) ((bbmsl10.tfm 0)))
((TeX\ Blackboard\ Bold Regular) ((bbm10.tfm 0)))
((TeX\ Blackboard\ Bold\ Sans Regular) ((bbmss10.tfm 0)))
((TeX\ Blackboard\ Bold\ Variant Regular) ((bbold10.tfm 0)))
((TeX\ Calligraphic\ Capitals Bold) ((cmbsy10.tfm 0)))
((TeX\ Calligraphic\ Capitals Regular) ((cmsy10.tfm 0)))
((TeX\ Double\ Stroke Regular) ((dsrom10.tfm 0)))
((TeX\ Double\ Stroke\ Sans Regular) ((dsss10.tfm 0)))
((TeX\ Euler\ Calligraphic Regular) ((euxm10.tfm 0)))
((TeX\ Gyre\ Chorus Regular) ((texgyrechorus-mediumitalic.otf 0)))
((TeX\ Gyre\ Heros Bold) ((texgyreheros-bold.otf 0)))
((TeX\ Gyre\ Heros Bold\ Italic) ((texgyreheros-bolditalic.otf 0)))
((TeX\ Gyre\ Heros Italic) ((texgyreheros-italic.otf 0)))
((TeX\ Gyre\ Heros Regular) ((texgyreheros-regular.otf 0)))
((TeX\ Gyre\ Pagella Bold) ((texgyrepagella-bold.otf 0)))
((TeX\ Gyre\ Pagella Bold\ Italic) ((texgyrepagella-bolditalic.otf 0)))
((TeX\ Gyre\ Pagella Italic) ((texgyrepagella-italic.otf 0)))
((TeX\ Gyre\ Pagella Regular) ((texgyrepagella-regular.otf 0)))
((TeX\ Gyre\ Pagella\ Math Regular) ((texgyrepagella-math.otf 0)))
((TeX\ Gyre\ Termes Bold) ((texgyretermes-bold.otf 0)))
((TeX\ Gyre\ Termes Bold\ Italic) ((texgyretermes-bolditalic.otf 0)))
((TeX\ Gyre\ Termes Italic) ((texgyretermes-italic.otf 0)))
((TeX\ Gyre\ Termes Regular) ((texgyretermes-regular.otf 0)))
((TeX\ Gyre\ Termes\ Math Regular) ((texgyretermes-math.otf 0)))
((TeX\ Ralph\ Smith Regular) ((rsfs10.tfm 0)))
((TeXmacs\ Avant\ Garde Bold) ((avant-garde-bx10.tfm 0)))
((TeXmacs\ Avant\ Garde Bold\ Italic) ((avant-garde-bi10.tfm 0)))
((TeXmacs\ Avant\ Garde Italic) ((avant-garde-ti10.tfm 0)))
((TeXmacs\ Avant\ Garde Regular) ((avant-garde-rm10.tfm 0)))
((TeXmacs\ Bookman Bold) ((bookman-bx10.tfm 0)))
((TeXmacs\ Bookman Bold\ Italic) ((bookman-bi10.tfm 0)))
((TeXmacs\ Bookman Italic) ((bookman-ti10.tfm 0)))
((TeXmacs\ Bookman Regular) ((bookman-rm10.tfm 0)))
((TeXmacs\ Computer\ Modern Bold) ((ecbx10.tfm 0)))
((TeXmacs\ Computer\ Modern Bold\ Condensed) ((ecrb10.tfm 0)))
((TeXmacs\ Computer\ Modern Bold\ Italic) ((ecbi10.tfm 0)))
((TeXmacs\ Computer\ Modern Bold\ Oblique) ((ecbl10.tfm 0)))
((TeXmacs\ Computer\ Modern Bold\ Oblique\ SmallCaps) ((ecoc10.tfm 0)))
((TeXmacs\ Computer\ Modern Bold\ SmallCaps) ((ecxc10.tfm 0)))
((TeXmacs\ Computer\ Modern Italic) ((ecti10.tfm 0)))
((TeXmacs\ Computer\ Modern Long) ((ecdh10.tfm 0)))
((TeXmacs\ Computer\ Modern Oblique) ((ecsl10.tfm 0)))
((TeXmacs\ Computer\ Modern Regular) ((ecrm10.tfm 0)))
((TeXmacs\ Computer\ Modern SmallCaps) ((eccc10.tfm 0)))
((TeXmacs\ Computer\ Modern\ Mono Italic\ Proportional) ((ecvi10.tfm 0)))
((TeXmacs\ Computer\ Modern\ Mono Oblique) ((ecst10.tfm 0)))
((TeXmacs\ Computer\ Modern\ Mono Proportional) ((ecvt10.tfm 0)))
((TeXmacs\ Computer\ Modern\ Mono Regular) ((ectt10.tfm 0)))
((TeXmacs\ Computer\ Modern\ Mono SmallCaps) ((ectc10.tfm 0)))
((TeXmacs\ Computer\ Modern\ Sans Bold) ((ecsx10.tfm 0)))
((TeXmacs\ Computer\ Modern\ Sans Bold\ Oblique) ((ecso10.tfm 0)))
((TeXmacs\ Computer\ Modern\ Sans Oblique) ((ecsi10.tfm 0)))
((TeXmacs\ Computer\ Modern\ Sans Regular) ((ecss10.tfm 0)))
((TeXmacs\ Concrete Bold) ((ecbx10.tfm 0)))
((TeXmacs\ Concrete Bold\ Condensed) ((ecrb10.tfm 0)))
((TeXmacs\ Concrete Bold\ Italic) ((ecbi10.tfm 0)))
((TeXmacs\ Concrete Bold\ Oblique) ((ecbl10.tfm 0)))
((TeXmacs\ Concrete Italic) ((eoti10.tfm 0)))
((TeXmacs\ Concrete Oblique) ((eosl10.tfm 0)))
((TeXmacs\ Concrete Regular) ((eorm10.tfm 0)))
((TeXmacs\ Concrete SmallCaps) ((eocc10.tfm 0)))
((TeXmacs\ Concrete\ Mono Proportional) ((ecvt10.tfm 0)))
((TeXmacs\ Concrete\ Mono Regular) ((ectt10.tfm 0)))
((TeXmacs\ Concrete\ Mono SmallCaps) ((ectc10.tfm 0)))
((TeXmacs\ Concrete\ Sans Bold) ((ecsx10.tfm 0)))
((TeXmacs\ Concrete\ Sans Regular) ((ecss10.tfm 0)))
((TeXmacs\ Courier Bold) ((courier-bx10.tfm 0)))
((TeXmacs\ Courier Bold\ Italic) ((courier-bi10.tfm 0)))
((TeXmacs\ Courier Italic) ((courier-ti10.tfm 0)))
((TeXmacs\ Courier Regular) ((courier-rm10.tfm 0)))
((TeXmacs\ Euler Bold) ((eufb10.tfm 0)))
((TeXmacs\ Euler Regular) ((eufm10.tfm 0)))
((TeXmacs\ Euler\ New\ Roman Bold) ((eurb10.tfm 0)))
((TeXmacs\ Euler\ New\ Roman Regular) ((eurm10.tfm 0)))
((TeXmacs\ Helvetica Bold) ((helvetica-bx10.tfm 0)))
((TeXmacs\ Helvetica Bold\ Italic) ((helvetica-bi10.tfm 0)))
((TeXmacs\ Helvetica Italic) ((helvetica-ti10.tfm 0)))
((TeXmacs\ Helvetica Regular) ((helvetica-rm10.tfm 0)))
((TeXmacs\ New\ Century\ Schoolbook Bold) ((nc-schoolbook-bx10.tfm 0)))
((TeXmacs\ New\ Century\ Schoolbook Bold\ Italic) ((nc-schoolbook-bi10.tfm 0)))
((TeXmacs\ New\ Century\ Schoolbook Italic) ((nc-schoolbook-ti10.tfm 0)))
((TeXmacs\ New\ Century\ Schoolbook Regular) ((nc-schoolbook-rm10.tfm 0)))
((TeXmacs\ Palatino Bold) ((palatino-bx10.tfm 0)))
((TeXmacs\ Palatino Bold\ Italic) ((palatino-bi10.tfm 0)))
((TeXmacs\ Palatino Bold\ Oblique) ((palatino-bl10.tfm 0)))
((TeXmacs\ Palatino Bold\ SmallCaps) ((palatino-xc10.tfm 0)))
((TeXmacs\ Palatino Italic) ((palatino-ti10.tfm 0)))
((TeXmacs\ Palatino Oblique) ((palatino-sl10.tfm 0)))
((TeXmacs\ Palatino Regular) ((palatino-rm10.tfm 0)))
((TeXmacs\ Palatino SmallCaps) ((palatino-cc10.tfm 0)))
((TeXmacs\ Times Bold) ((times-bx10.tfm 0)))
((TeXmacs\ Times Bold\ Italic) ((times-bi10.tfm 0)))
((TeXmacs\ Times Bold\ Oblique) ((times-bl10.tfm 0)))
((TeXmacs\ Times Bold\ SmallCaps) ((times-xc10.tfm 0)))
((TeXmacs\ Times Italic) ((times-ti10.tfm 0)))
((TeXmacs\ Times Oblique) ((times-sl10.tfm 0)))
((TeXmacs\ Times Regular) ((times-rm10.tfm 0)))
((TeXmacs\ Times SmallCaps) ((times-cc10.tfm 0)))
((Times\ New\ Roman Bold) ((Times\ New\ Roman\ Bold.ttf 0)))
((Times\ New\ Roman Bold\ Italic) ((Times\ New\ Roman\ Bold\ Italic.ttf 0)))
((Times\ New\ Roman Italic) ((Times\ New\ Roman\ Italic.ttf 0)))
((Times\ New\ Roman Regular) ((Times\ New\ Roman.ttf 0)))
((Trebuchet\ MS Bold) ((Trebuchet\ MS\ Bold.ttf 0)))
((Trebuchet\ MS Bold\ Italic) ((Trebuchet\ MS\ Bold\ Italic.ttf 0)))
((Trebuchet\ MS Italic) ((Trebuchet\ MS\ Italic.ttf 0)))
((Trebuchet\ MS Regular) ((Trebuchet\ MS.ttf 0)))
((Verdana Bold) ((Verdana\ Bold.ttf 0)))
((Verdana Bold\ Italic) ((Verdana\ Bold\ Italic.ttf 0)))
((Verdana Italic) ((Verdana\ Italic.ttf 0)))
((Verdana Regular) ((Verdana.ttf 0)))
((Webdings Regular) ((Webdings.ttf 0)))
((Wingdings Regular) ((Wingdings.ttf 0)))
((Wingdings\ 2 Regular) ((Wingdings\ 2.ttf 0)))
((Wingdings\ 3 Regular) ((Wingdings\ 3.ttf 0)))
((Zapf\ Dingbats Regular) ((ZapfDingbats.ttf 0)))
((Zapfino Regular) ((Zapfino.ttf 0)))
